import React from "react";

const Productdata = [
    { "id": 1, "name": "AeroStream Wireless Mouse", "price": 45.00, "category": "Electronics", "stock": 120, "rating": 4.5, "description": "High-precision ergonomic mouse with silent clicks." },
    { "id": 2, "name": "Lumina RGB Keyboard", "price": 89.99, "category": "Electronics", "stock": 45, "rating": 4.8, "description": "Mechanical keyboard with customizable backlight zones." },
    { "id": 3, "name": "Zenith 4K Monitor", "price": 320.50, "category": "Electronics", "stock": 15, "rating": 4.7, "description": "27-inch Ultra HD display with vibrant color accuracy." },
    { "id": 4, "name": "SonicBlast Bluetooth Speaker", "price": 55.00, "category": "Electronics", "stock": 88, "rating": 4.2, "description": "Water-resistant portable speaker with deep bass." },
    { "id": 5, "name": "Vantage Laptop Stand", "price": 29.99, "category": "Office", "stock": 200, "rating": 4.6, "description": "Aluminum adjustable stand for better neck posture." },
    { "id": 6, "name": "Bistro Electric Kettle", "price": 39.00, "category": "Home", "stock": 34, "rating": 4.4, "description": "Fast-boil stainless steel kettle with auto-shutoff." },
    { "id": 7, "name": "Titan Gym Dumbbells", "price": 110.00, "category": "Fitness", "stock": 12, "rating": 4.9, "description": "Set of 2 adjustable dumbbells for home workouts." },
    { "id": 8, "name": "CloudWalk Running Shoes", "price": 75.00, "category": "Fashion", "stock": 60, "rating": 4.3, "description": "Breathable mesh sneakers with cushioned soles." },
    { "id": 9, "name": "Orbit Smart Watch", "price": 199.00, "category": "Electronics", "stock": 25, "rating": 4.5, "description": "Tracks heart rate, sleep, and GPS movements." },
    { "id": 10, "name": "Velvet Comfort Pillow", "price": 25.50, "category": "Home", "stock": 150, "rating": 4.1, "description": "Memory foam pillow with a cooling gel layer." },
    { "id": 11, "name": "GlowUp Face Serum", "price": 18.00, "category": "Beauty", "stock": 300, "rating": 4.7, "description": "Vitamin C serum for radiant and hydrated skin." },
    { "id": 12, "name": "Summit Backpack 30L", "price": 65.00, "category": "Outdoors", "stock": 42, "rating": 4.6, "description": "Durable hiking backpack with rain cover." },
    { "id": 13, "name": "JavaMaster Coffee Press", "price": 32.00, "category": "Home", "stock": 75, "rating": 4.8, "description": "French press for the perfect morning brew." },
    { "id": 14, "name": "IronCore Yoga Mat", "price": 22.99, "category": "Fitness", "stock": 110, "rating": 4.4, "description": "Non-slip 6mm thick mat for yoga and pilates." },
    { "id": 15, "name": "PureSound Earbuds", "price": 129.00, "category": "Electronics", "stock": 55, "rating": 4.5, "description": "Active noise canceling true wireless earbuds." },
    { "id": 16, "name": "Urban Denim Jacket", "price": 55.00, "category": "Fashion", "stock": 30, "rating": 4.2, "description": "Classic blue denim jacket with a modern fit." },
    { "id": 17, "name": "EcoGreen Bamboo Plate Set", "price": 45.00, "category": "Home", "stock": 90, "rating": 4.6, "description": "Sustainable 4-piece dinnerware set." },
    { "id": 18, "name": "PowerUp 20k Power Bank", "price": 49.99, "category": "Electronics", "stock": 140, "rating": 4.7, "description": "High-capacity portable charger with fast charging." },
    { "id": 19, "name": "Chef's Choice Knife Set", "price": 85.00, "category": "Home", "stock": 20, "rating": 4.9, "description": "Professional grade 5-piece stainless steel knives." },
    { "id": 20, "name": "Flexi-Desk Lamp", "price": 19.50, "category": "Office", "stock": 65, "rating": 4.3, "description": "LED desk lamp with 3 brightness levels." },
    { "id": 21, "name": "Trek-Safe First Aid Kit", "price": 24.00, "category": "Outdoors", "stock": 200, "rating": 4.8, "description": "Compact emergency kit for hikers and travelers." },
    { "id": 22, "name": "PixelPro Web Cam", "price": 69.00, "category": "Electronics", "stock": 50, "rating": 4.4, "description": "1080p HD camera with dual microphones." },
    { "id": 23, "name": "CozyKnit Throw Blanket", "price": 35.00, "category": "Home", "stock": 85, "rating": 4.5, "description": "Soft wool-blend blanket for winter nights." },
    { "id": 24, "name": "SteadyShot Tripod", "price": 42.00, "category": "Electronics", "stock": 40, "rating": 4.1, "description": "Lightweight tripod for phones and DSLR cameras." },
    { "id": 25, "name": "PulseFit Jump Rope", "price": 12.99, "category": "Fitness", "stock": 300, "rating": 4.6, "description": "Adjustable speed rope for cardio training." },
    { "id": 26, "name": "GripMaster Gaming Mousepad", "price": 15.00, "category": "Electronics", "stock": 210, "rating": 4.7, "description": "Extra-large cloth pad with anti-fray edges." },
    { "id": 27, "name": "Retro Vinyl Player", "price": 145.00, "category": "Home", "stock": 18, "rating": 4.8, "description": "Turntable with built-in speakers and Bluetooth." },
    { "id": 28, "name": "HydroCool Water Bottle", "price": 28.00, "category": "Fitness", "stock": 130, "rating": 4.5, "description": "Insulated bottle that keeps drinks cold for 24h." },
    { "id": 29, "name": "LushLavender Candle", "price": 14.50, "category": "Home", "stock": 250, "rating": 4.3, "description": "Scented soy wax candle for relaxation." },
    { "id": 30, "name": "SmartPlug WiFi Socket", "price": 12.00, "category": "Electronics", "stock": 400, "rating": 4.4, "description": "Control your appliances via mobile app." },
    { "id": 31, "name": "Shield-X Screen Protector", "price": 9.99, "category": "Electronics", "stock": 500, "rating": 4.6, "description": "Tempered glass for latest smartphone models." },
    { "id": 32, "name": "BoldMove Gym Bag", "price": 38.00, "category": "Fitness", "stock": 70, "rating": 4.5, "description": "Spacious bag with separate shoe compartment." },
    { "id": 33, "name": "SilkSleep Eye Mask", "price": 15.99, "category": "Beauty", "stock": 180, "rating": 4.7, "description": "100% mulberry silk mask for better sleep." },
    { "id": 34, "name": "Titanium Spork", "price": 8.00, "category": "Outdoors", "stock": 150, "rating": 4.2, "description": "Ultralight camping utensil for travelers." },
    { "id": 35, "name": "FocusFlow White Noise Machine", "price": 45.00, "category": "Home", "stock": 60, "rating": 4.4, "description": "Soothing sounds to help sleep and concentration." },
    { "id": 36, "name": "EverLast Leather Belt", "price": 32.00, "category": "Fashion", "stock": 100, "rating": 4.8, "description": "Full-grain leather belt with silver buckle." },
    { "id": 37, "name": "QuickDry Towel Set", "price": 26.00, "category": "Home", "stock": 115, "rating": 4.5, "description": "Microfiber towels perfect for travel and gym." },
    { "id": 38, "name": "NanoDrive 128GB Flash Drive", "price": 19.99, "category": "Electronics", "stock": 300, "rating": 4.3, "description": "Compact USB 3.0 drive for fast data transfer." },
    { "id": 39, "name": "Aura Humidifier", "price": 48.00, "category": "Home", "stock": 45, "rating": 4.6, "description": "Cool mist humidifier with essential oil tray." },
    { "id": 40, "name": "GripFit Resistance Bands", "price": 16.50, "category": "Fitness", "stock": 220, "rating": 4.7, "description": "Set of 5 levels for strength training." },
    { "id": 41, "name": "ClearView Binoculars", "price": 88.00, "category": "Outdoors", "stock": 25, "rating": 4.4, "description": "8x42 magnification for bird watching." },
    { "id": 42, "name": "StylePoint Polo Shirt", "price": 24.00, "category": "Fashion", "stock": 140, "rating": 4.1, "description": "Cotton blend polo with a slim fit design." },
    { "id": 43, "name": "SafeKey Padlock", "price": 18.00, "category": "Home", "stock": 95, "rating": 4.2, "description": "Heavy-duty steel lock with weather resistance." },
    { "id": 44, "name": "Mistify Spray Bottle", "price": 7.50, "category": "Home", "stock": 400, "rating": 4.5, "description": "Continuous fine mist spray for plants or hair." },
    { "id": 45, "name": "LogiType Keyboard Case", "price": 79.00, "category": "Electronics", "stock": 35, "rating": 4.6, "description": "Protective case with integrated keyboard for tablets." },
    { "id": 46, "name": "PeakPerformance Protein Shaker", "price": 14.00, "category": "Fitness", "stock": 180, "rating": 4.4, "description": "BPA-free shaker with whisk ball." },
    { "id": 47, "name": "VividHue Watercolor Set", "price": 35.00, "category": "Art", "stock": 55, "rating": 4.8, "description": "24 vibrant colors with professional brushes." },
    { "id": 48, "name": "SteadyHand Stylus", "price": 22.00, "category": "Electronics", "stock": 120, "rating": 4.3, "description": "Precision pen for touch screens and drawing." },
    { "id": 49, "name": "AirClean Desktop Purifier", "price": 95.00, "category": "Home", "stock": 22, "rating": 4.7, "description": "HEPA filter purifier for small rooms." },
    { "id": 50, "name": "CozyStep Slippers", "price": 19.99, "category": "Fashion", "stock": 160, "rating": 4.2, "description": "Fleece-lined slippers with rubber soles." },
    { "id": 51, "name": "PowerCord 6ft Cable", "price": 12.00, "category": "Electronics", "stock": 500, "rating": 4.5, "description": "Braided USB-C to USB-C fast charging cable." },
    { "id": 52, "name": "OpticClear Lens Cleaner", "price": 6.99, "category": "Beauty", "stock": 350, "rating": 4.6, "description": "Anti-fog spray for glasses and camera lenses." },
    { "id": 53, "name": "TrailMaster Compass", "price": 15.00, "category": "Outdoors", "stock": 80, "rating": 4.4, "description": "High-accuracy navigation tool for hiking." },
    { "id": 54, "name": "BrewReady Coffee Beans", "price": 21.00, "category": "Home", "stock": 110, "rating": 4.9, "description": "1lb medium roast organic arabica beans." },
    { "id": 55, "name": "EcoBag Canvas Tote", "price": 10.00, "category": "Fashion", "stock": 400, "rating": 4.3, "description": "Reusable heavy-duty cotton tote bag." },
    { "id": 56, "name": "SoundGate Wall Mount", "price": 28.00, "category": "Electronics", "stock": 60, "rating": 4.5, "description": "Universal soundbar mount for home theaters." },
    { "id": 57, "name": "FreshMelt Wax Warmer", "price": 22.50, "category": "Home", "stock": 45, "rating": 4.2, "description": "Electric heater for fragrant wax melts." },
    { "id": 58, "name": "SwiftCut Scissors", "price": 9.00, "category": "Office", "stock": 200, "rating": 4.6, "description": "Precision stainless steel craft scissors." },
    { "id": 59, "name": "RuggedPhone Case", "price": 25.00, "category": "Electronics", "stock": 150, "rating": 4.7, "description": "Military-grade drop protection case." },
    { "id": 60, "name": "NightLight Plug-in", "price": 11.00, "category": "Home", "stock": 300, "rating": 4.4, "description": "LED sensor light for hallways and kids' rooms." },
    { "id": 61, "name": "GripTape Tennis Overgrip", "price": 12.00, "category": "Fitness", "stock": 180, "rating": 4.5, "description": "Pack of 3 absorbent non-slip grips." },
    { "id": 62, "name": "SlateGrey Notebook", "price": 16.00, "category": "Office", "stock": 220, "rating": 4.8, "description": "Hardcover dotted journal for bulleting." },
    { "id": 63, "name": "ClearCoat Nail Polish", "price": 8.50, "category": "Beauty", "stock": 250, "rating": 4.1, "description": "Fast-drying high-shine top coat." },
    { "id": 64, "name": "SnapDry Dish Rack", "price": 34.00, "category": "Home", "stock": 40, "rating": 4.5, "description": "Collapsible space-saving drying rack." },
    { "id": 65, "name": "BioFoam Roller", "price": 24.00, "category": "Fitness", "stock": 90, "rating": 4.6, "description": "High-density foam for muscle recovery." },
    { "id": 66, "name": "Digital Food Scale", "price": 19.00, "category": "Home", "stock": 130, "rating": 4.7, "description": "Accurate scale with tare function for cooking." },
    { "id": 67, "name": "AeroFan Desk Fan", "price": 27.00, "category": "Office", "stock": 75, "rating": 4.3, "description": "USB-powered quiet cooling fan." },
    { "id": 68, "name": "EverGlow Lantern", "price": 32.00, "category": "Outdoors", "stock": 50, "rating": 4.8, "description": "Solar-powered LED camping lantern." },
    { "id": 69, "name": "TrueFlex Phone Stand", "price": 14.00, "category": "Electronics", "stock": 210, "rating": 4.4, "description": "Flexible gooseneck holder for desk or bed." },
    { "id": 70, "name": "Linen Napkin Set", "price": 22.00, "category": "Home", "stock": 100, "rating": 4.5, "description": "Set of 6 premium linen table napkins." },
    { "id": 71, "name": "QuickFix Screwdriver Set", "price": 18.50, "category": "Office", "stock": 140, "rating": 4.6, "description": "Small precision kit for electronics repair." },
    { "id": 72, "name": "SunShield Sunscreen", "price": 14.99, "category": "Beauty", "stock": 200, "rating": 4.7, "description": "SPF 50 mineral sunscreen for face." },
    { "id": 73, "name": "GripPro Golf Glove", "price": 16.00, "category": "Fitness", "stock": 110, "rating": 4.2, "description": "Breathable leather glove for left-handed golfers." },
    { "id": 74, "name": "UrbanBeanie Hat", "price": 18.00, "category": "Fashion", "stock": 150, "rating": 4.4, "description": "Soft acrylic knit beanie for winter." },
    { "id": 75, "name": "AquaPure Filter Pitcher", "price": 29.00, "category": "Home", "stock": 65, "rating": 4.6, "description": "Removes chlorine and impurities from tap water." },
    { "id": 76, "name": "SoftTouch Mousepad", "price": 12.00, "category": "Electronics", "stock": 300, "rating": 4.1, "description": "Gel-filled wrist rest for comfort." },
    { "id": 77, "name": "VibeEar Wired Buds", "price": 15.00, "category": "Electronics", "stock": 400, "rating": 4.0, "description": "Classic in-ear headphones with microphone." },
    { "id": 78, "name": "Chef's Apron", "price": 24.50, "category": "Home", "stock": 85, "rating": 4.5, "description": "Heavy-duty canvas apron with pockets." },
    { "id": 79, "name": "MiniProjector Pro", "price": 125.00, "category": "Electronics", "stock": 15, "rating": 4.3, "description": "Portable cinema projector with HDMI input." },
    { "id": 80, "name": "EcoMat TPE Yoga Mat", "price": 38.00, "category": "Fitness", "stock": 50, "rating": 4.8, "description": "Dual-layer eco-friendly yoga mat." },
    { "id": 81, "name": "DeskOrganizer Tray", "price": 21.00, "category": "Office", "stock": 120, "rating": 4.6, "description": "Mesh steel tray for files and stationery." },
    { "id": 82, "name": "SmartBulb Color", "price": 15.99, "category": "Electronics", "stock": 250, "rating": 4.5, "description": "App-controlled LED bulb with 16M colors." },
    { "id": 83, "name": "Pebble Wireless Mouse", "price": 29.00, "category": "Electronics", "stock": 95, "rating": 4.7, "description": "Slim, silent, and modern design." },
    { "id": 84, "name": "HydroFlask 21oz", "price": 34.00, "category": "Outdoors", "stock": 110, "rating": 4.9, "description": "Vacuum insulated standard mouth bottle." },
    { "id": 85, "name": "CoreStrength Ab Roller", "price": 19.99, "category": "Fitness", "stock": 140, "rating": 4.4, "description": "Sturdy wheel for core muscle building." },
    { "id": 86, "name": "SilkScarf Print", "price": 45.00, "category": "Fashion", "stock": 40, "rating": 4.8, "description": "Hand-painted 100% silk neck scarf." },
    { "id": 87, "name": "CleanWave Sonic Toothbrush", "price": 65.00, "category": "Beauty", "stock": 55, "rating": 4.7, "description": "Rechargeable brush with 5 cleaning modes." },
    { "id": 88, "name": "RusticWall Clock", "price": 32.00, "category": "Home", "stock": 30, "rating": 4.3, "description": "12-inch wooden clock with silent movement." },
    { "id": 89, "name": "SafeStep Bath Mat", "price": 18.00, "category": "Home", "stock": 150, "rating": 4.5, "description": "Non-slip absorbent bathroom rug." },
    { "id": 90, "name": "ChargePad Wireless", "price": 22.00, "category": "Electronics", "stock": 200, "rating": 4.4, "description": "Qi-certified 15W fast wireless charger." },
    { "id": 91, "name": "FlexiWorkout Pants", "price": 42.00, "category": "Fitness", "stock": 80, "rating": 4.6, "description": "High-waist moisture-wicking leggings." },
    { "id": 92, "name": "NanoClean Cloths", "price": 12.50, "category": "Home", "stock": 300, "rating": 4.7, "description": "Pack of 12 lint-free microfiber cloths." },
    { "id": 93, "name": "BrewMist Tea Infuser", "price": 9.99, "category": "Home", "stock": 180, "rating": 4.3, "description": "Silicone and stainless steel leaf infuser." },
    { "id": 94, "name": "Traveler's Neck Pillow", "price": 25.00, "category": "Outdoors", "stock": 100, "rating": 4.4, "description": "Contoured memory foam pillow for flights." },
    { "id": 95, "name": "KeyFinder Bluetooth Tag", "price": 19.00, "category": "Electronics", "stock": 250, "rating": 4.2, "description": "Smart tracker to find keys and wallets." },
    { "id": 96, "name": "Gourmet Salt Set", "price": 28.00, "category": "Home", "stock": 60, "rating": 4.8, "description": "Collection of 4 artisanal finishing salts." },
    { "id": 97, "name": "ClipOn Reading Light", "price": 14.00, "category": "Home", "stock": 130, "rating": 4.5, "description": "Rechargeable light for book lovers." },
    { "id": 98, "name": "PureMist Air Freshener", "price": 15.00, "category": "Home", "stock": 200, "rating": 4.1, "description": "Automatic spray with citrus scent." },
    { "id": 99, "name": "FocusTimer Cube", "price": 18.00, "category": "Office", "stock": 85, "rating": 4.6, "description": "Gravity-sensing productivity timer." },
    { "id": 100, "name": "ZenGarden Desk Kit", "price": 24.99, "category": "Office", "stock": 45, "rating": 4.7, "description": "Miniature sand garden for stress relief." }
]

export default Productdata;